name: Build and deploy docs

on:
  push:
    # Run when a change to these files is pushed to any of these branches.
    # When you copy this into your repo, you should:
    # - Replace 'master' with the name of your repo's primary branch, if it's not master (e.g.,
    #   main)
    # - Delete 'add-github-workflows-with-tmp-docs' 
    # - Add any branches you refer to with DocsVersion(..., ref=*) in version_list.py
    branches: ['master', 'add-github-workflows-with-tmp-docs']
    # paths:
    #   - '.github/workflows/docs-build-and-deploy.yml'
    #   - '.github/workflows/docs-build_to_publish-optionally-deploy.yml'
    #   - 'doc/**'
    # When you copy this into your repo:
    # - Uncomment the "paths" block above
    # - Make sure to add any files that you "include" in your docs that live outside doc/.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build-and-deploy:
    name: Call reusable workflow with deploy true

    # Only run on upstream repository.
    # When you copy this into your repo, replace this with yours. Case-sensitive!
    if: ${{ github.repository == 'ESMCI/doc-builder' }}

    # Grant the GITHUB_TOKEN the write scopes needed to deploy to GitHub Pages.
    permissions:
      contents: read
      pages: write
      id-token: write

    uses: ./.github/workflows/docs-build_to_publish-optionally-deploy.yml
    with:
      deploy: true
